Squashed some bugs, added support for ELF and other executables
geekscrapy/binGraph pull request #1
Opened 2018-09-27 02:34 UTC by 0ki

I don't have the pefile lib, so these functions probably need handling with pefile added to them:

    def get_physical_from_elf_v(self, rva)		
    def get_elf_ep(self)

2018-09-27 07:04 UTC, geekscrapy commented
Thanks for that!
In regards to pefile lib, it doesn't handle elf so there is no way to handle it.

To be honest, in a future version I may just remove pefile as it was something someone asked for, but then I discovered lief which was much more compatible...

Thanks again, I'll review it asap

2018-10-02 20:20 UTC, geekscrapy commented on binGraph.py
> +parser.add_argument('-w', '--watermark', action='store_true', help='Add watermark to image files')
I would like to keep the attribution where possible. I don't mind setting this --nowatermark and default is False with store_true - it is good to have an option to remove it, but not as a default. Graphs can be created standalone (by running the graph.py module) and these are generated without the watermark.

2018-10-02 20:20 UTC, geekscrapy commented on binGraph.py
> +        if args.watermark:
As above

2018-10-02 20:36 UTC, 0ki commented
Watermark positioning code is buggy and often puts it on top of other labels. Until it's fixed I recommend the watermark defaults to off.

2018-10-02 21:29 UTC, geekscrapy reviewed
> Watermark positioning code is buggy and often puts it on top of other labels. Until it's fixed I recommend the watermark defaults to off.

Agreed - I'll fix it once this commit is in

#2 issue created

2018-10-02 21:29 UTC, geekscrapy commented on graphs/ent/graph.py
> +        self.bin, self.type, self.lib = None, None, None
These (apart from self.type) are defined on line 368. Can you make a commit which removes that line, as I agree it is better to define them here

2018-10-02 21:29 UTC, geekscrapy commented on graphs/ent/graph.py
> +        return s_name[0:20] #long sections names upset matplotlib
👍  Good catch!

2018-10-02 21:29 UTC, geekscrapy commented on graphs/ent/graph.py
> +                    if section.name.startswith( ('.fini', '.gnu', '.note.') ):
I'd like to still keep these sections as they are valid code execution blocks. Please can you remove this "if"? The analyst needs to rely on having all the information shown

2018-10-02 21:29 UTC, geekscrapy commented on graphs/ent/graph.py
> +                    if section_offset - printed_section_offset < 15:
Is this to limit the number of section titles shown? I would prefer to keep all the sections shown please, otherwise, the analyst cannot rely on the tool showing the same results.

2018-10-02 21:29 UTC, geekscrapy commented on graphs/ent/graph.py
> +                    self.type = '_unk_exec'
This _should_ never hit as if lief cannot parse the file it will throw a _pylief.bad_file exception

2018-10-02 21:29 UTC, geekscrapy commented on graphs/ent/graph.py
> +					self.bin = None
This is checked as None above and so should not need to be redefined

2018-10-02 21:29 UTC, geekscrapy commented on graphs/ent/graph.py
> +            elif bp.type == '_unk_exec':
This section will never be hit as if the binary blob cannot be parsed it is returned from ```bp.type```  as None and will then be parsed as a blob

2018-10-02 21:44 UTC, geekscrapy requested changes
Thanks again for the pull request!

I've added a few comments, if you could review them that would be great. I think there might be an issue with the new __parse_bin logic surrounding _unk_exec mainly?

In regards to not printing all the section names, I'd like to keep them all for now as it is expected by the analyst to show all sections. I agree there needs to be a better way to show them (maybe I will layer them above and below - like camel case if they are going to overlap), but for now I'd like to keep it simple and show them all. Also, if they are that close, the entropy between them probably doesn't matter anyway, and I expect the analyst already knows all the section names. Unless of course it's a huge binary - which I have not actually tried!

Lastly, I try and use 4 spaced indents with his porject and notice that some of the committed code uses tabs, are you able to convert it to 4 spaces please? It makes the code a bit more uniform and in some places, easier to read.

Thanks!

2018-10-15 22:54 UTC, geekscrapy commented
Hi, unfortunately, I'm going to have to close this pull request as the project has moved on a bit and I was in the process of removing pefile and therefore the bin_proxy object. I have integrated the code I could though.

I thank you again for the pull, and sorry I couldn't merge using this request, I'm fairly new to code collaboration.

2018-10-15 22:54 UTC, closed without merging